graph LR
  N899599816["Forest: contoso.com"] -->|"F001 ContainsDomain"| N854968690["Domain: contoso.com"]
  N899599816["Forest: contoso.com"] -->|"F002 ContainsDomain"| N1943507165["Domain: corp.contoso.com"]
  N899599816["Forest: contoso.com"] -->|"F003 SchemaMaster"| N199084092["DomainController: dc01.contoso.com"]
  N899599816["Forest: contoso.com"] -->|"F004 DomainNamingMaster"| N199084092["DomainController: dc01.contoso.com"]
  N899599816["Forest: contoso.com"] -->|"F005 HasNamingContext"| N1464907912["NamingContext: DC=contoso,DC=com"]
  N899599816["Forest: contoso.com"] -->|"F006 HasNamingContext"| N1401746646["NamingContext: CN=Configuration,DC=contoso,DC=com"]
  N899599816["Forest: contoso.com"] -->|"F007 HasNamingContext"| N2096178016["NamingContext: CN=Schema,CN=Configuration,DC=contoso,DC=com"]
  N899599816["Forest: contoso.com"] -->|"F008 HasNamingContext"| N1950922606["NamingContext: DC=DomainDnsZones,DC=contoso,DC=com"]
  N899599816["Forest: contoso.com"] -->|"F009 HasNamingContext"| N2050091115["NamingContext: DC=ForestDnsZones,DC=contoso,DC=com"]
  N899599816["Forest: contoso.com"] -->|"F010 HasDnsApplicationPartition"| N1596726848["DnsApplicationPartition: DC=DomainDnsZones,DC=contoso,DC=com"]
  N1596726848["DnsApplicationPartition: DC=DomainDnsZones,DC=contoso,DC=com"] -->|"F011 ReplicatedTo"| N291446259["DomainController: DC01"]
  N1596726848["DnsApplicationPartition: DC=DomainDnsZones,DC=contoso,DC=com"] -->|"F012 ReplicatedTo"| N1218339112["DomainController: DC02"]
  N899599816["Forest: contoso.com"] -->|"F013 HasDnsApplicationPartition"| N998615763["DnsApplicationPartition: DC=ForestDnsZones,DC=contoso,DC=com"]
  N998615763["DnsApplicationPartition: DC=ForestDnsZones,DC=contoso,DC=com"] -->|"F014 ReplicatedTo"| N1729334957["DomainController: CDC01"]
  N998615763["DnsApplicationPartition: DC=ForestDnsZones,DC=contoso,DC=com"] -->|"F015 ReplicatedTo"| N291446259["DomainController: DC01"]
  N899599816["Forest: contoso.com"] -->|"F016 EnabledOptionalFeature"| N1688250616["OptionalFeature: Recycle Bin Feature"]
  N899599816["Forest: contoso.com"] -->|"F017 ConfiguredSuffix"| N632276175["Suffix: contoso.com"]
  N899599816["Forest: contoso.com"] -->|"F018 ConfiguredSuffix"| N1507606204["Suffix: contoso.net"]
